### ISSUE TITLE
Use consistent wording when referring to support

### ISSUE THREAD

**Issue by Marcono1234** [mojira/helper-messages#126]
The messages mentioning Mojang or Community Support are currently not consistent:
- Most are using an article, but not all: "contact **the** support" vs. "contact support" (not sure what is the correct way, if any)
  - With article:
    - https://github.com/mojira/helper-messages/blob/e7264d5d87b12408075a12d3e1d373bbc7bfe980/assets/messages.yml#L358
    - https://github.com/mojira/helper-messages/blob/e7264d5d87b12408075a12d3e1d373bbc7bfe980/assets/messages.yml#L373
    - https://github.com/mojira/helper-messages/blob/e7264d5d87b12408075a12d3e1d373bbc7bfe980/assets/messages.yml#L459
    - https://github.com/mojira/helper-messages/blob/e7264d5d87b12408075a12d3e1d373bbc7bfe980/assets/messages.yml#L664
  - Without article:
    - https://github.com/mojira/helper-messages/blob/e7264d5d87b12408075a12d3e1d373bbc7bfe980/assets/messages.yml#L84
    - https://github.com/mojira/helper-messages/blob/e7264d5d87b12408075a12d3e1d373bbc7bfe980/assets/messages.yml#L1063
    - https://github.com/mojira/helper-messages/blob/e7264d5d87b12408075a12d3e1d373bbc7bfe980/assets/messages.yml#L1089
    - https://github.com/mojira/helper-messages/blob/e7264d5d87b12408075a12d3e1d373bbc7bfe980/assets/messages.yml#L1111
    - https://github.com/mojira/helper-messages/blob/e7264d5d87b12408075a12d3e1d373bbc7bfe980/assets/messages.yml#L1132
    - https://github.com/mojira/helper-messages/blob/e7264d5d87b12408075a12d3e1d373bbc7bfe980/assets/messages.yml#L1135
- Talks about "joining the [...] Discord" while all other messages say "contact [...] support":
https://github.com/mojira/helper-messages/blob/e7264d5d87b12408075a12d3e1d373bbc7bfe980/assets/messages.yml#L399
- Talks about "use the [...] Discord server" while all other messages say "contact [...] support":
https://github.com/mojira/helper-messages/blob/e7264d5d87b12408075a12d3e1d373bbc7bfe980/assets/messages.yml#L1063
- Says "visit [...] support" instead of "contact [...] support" and calls it "Minecraft Community Support" while all other messages only call it "Community Support":
https://github.com/mojira/helper-messages/blob/e7264d5d87b12408075a12d3e1d373bbc7bfe980/assets/messages.yml#L1132

So it would probably good to:
- [ ] Consistently use or don't use an article for "support". To the native speakers, what do you think would be better?
- [ ] Consistently use "contact [...] support" (instead of "join [...]" or "visit [...]")
- [ ] Consistently call it "Community Support"

**Comment by SPGoding** [comment]
Imo all three proposed changes are good.

**Comment by Marcono1234** [comment]
The first one was a choice between either using, or not using an article though 😄
Do you think 1) "contact the support" (with article) or 2) "contact support" (without article) is better / more correct?

**Comment by Pokechu22** [comment]
"contact support" sounds better to me; I'd only use the article for "contact the support team" or something like that.

**Comment by SPGoding** [comment]
🤦 Should've read the checklist carefully.

It's "Community Support" in this case, so I'd expect an article before it.

**Comment by Pokechu22** [comment]
Hm, I'm not sure.  To me, "contact Community Support" still sounds better than "contact the Community Support", but I can't really say why.

**Comment by violine1101** [comment]
Although I'm a non-native speaker I'd agree with that, the additional "the" sounds a bit unnatural to me.
