### ISSUE TITLE
Add a personal access token to GitHub Actions secrets

### ISSUE THREAD

**Issue by SPGoding** [mojira/helper-messages#23]
# Background
I'm trying to make the deploy process of this tool automated by using [GitHub Actions](https://github.com/features/actions) with the [github-pages-deploy-action](https://github.com/JamesIves/github-pages-deploy-action).

We need a token that has permission to write to the repository.

# The Problem

GitHub automatically creates a [`GITHUB_TOKEN`](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token) secret that we can use in the workflow. However, I just figured out that the `GITHUB_TOKEN` couldn't trigger a GitHub Pages build according to JamesIves/github-pages-deploy-action#5.

Therefore, we have to add a [personal access token](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line) that has write access to this repo. The thing is that only members with `admin` permission can create GitHub action secrets, so I'm opening this issue looking for help.

# To Resolve

1. [Create a personal access token](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line#creating-a-token) that has write permission (_I guess?_) to this repo.
2. [Add that token to this repo's secrets](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets). The name of this secret should be `ACCESS_TOKEN`, the value of it should be the token generated in the first step.
3. Merge #22.

**Comment by urielsalis** [comment]
Done

**Comment by SPGoding** [comment]
Thanks, all done.
The bot just deployed at 4695907f9f08eb62dabfa9a7788ab9a7a41c1432 :tada:
