### ISSUE TITLE
Remove ACCESS_TOKEN secret and revoke access token

### ISSUE THREAD

**Issue by Marcono1234** [mojira/helper-messages#45]
Now that #44 has been merged, the `ACCESS_TOKEN` secret should not be needed anymore and the person who previously created an access token (urielsalis?) can revoke it.
Effectively undoing #23.

However, **before doing this**, we should probably wait for the next commit on `master` to make sure that the changed GitHub action still works (worked on my fork at least).

**Comment by urielsalis** [comment]
PM me as soon as it works and I will revoke it

**Comment by SPGoding** [comment]
It works (61db10f09dd8c8f191fe2defe5dafabc1da6ce95)
