### ISSUE TITLE
No quick links for WEB project

### ISSUE THREAD

**Issue by SPGoding** [mojira/helper-messages#52]
E.g. [WEB-2376](https://bugs.mojang.com/browse/WEB-2376)

**Comment by O5X** [comment]
I'm not sure there needs to be to be honest. If I need a general message I usually just switch over to MCPE. How would the WEB quick links differ from the normal ones?

**Comment by NeunEinser** [comment]
Arisa is always using the message and quick links from the correct project, see linked ticket
