### ISSUE TITLE
Translate "wrong language" bot message into other languages

### ISSUE THREAD

**Issue by violine1101** [mojira/helper-messages#78]
For further convenience to the bug tracker users, it would be nice if the bot would be able to respond to a user whose ticket it closed for being in a wrong language.

We need to decide:
* Do we want to translate the messages in the first place?
* To which languages should the message be translated?
* Who can translate the message?

**Comment by SPGoding** [comment]
Some progress of translating the quick links part can be found in #56

**Comment by bemoty** [comment]
I would definitely translate the messages if possible and use English as fallback. As for "which languages should be translated" I'd just go for "the more the better" — as I've already said, I would just drop the Crowdin translators a message and ask them for their help, then add all the translations I get back from them. :)

**Comment by violine1101** [comment]
I believe by now the decision for
> * Do we want to translate the messages in the first place?

is a clear "no". Closing.

See also internal discussion @ `G01B5S71P8A/p1678813179978679`.
