### ISSUE TITLE
Add "Temporary Outage" message.

### ISSUE THREAD

**Issue by MikeUnverferth** [mojira/helper-messages#86]
It would be nice to be able to have a general message about transient connectivity issues (realms, servers, marketplace) and resolve these as invalid, somewhat like the "crash logged automatically" ones. Every time there's a realms outage a bunch of reports get submitted and having to then collect them and resolve as a duplicate or ask if the problem is still happening takes quite a lot of time.
Proposed message text:

*Thank you for your report.*
Temporary connectivity and service availability issues related to Marketplace, Realms, and Servers, are handled by the team outside the bug tracker.
Check [Mojang Status|https://twitter.com/MojangStatus] for official announcements, or [Downdetector|https://downdetector.com/status/minecraft] for community reported outages.
If there is no general outage, you are free to create a new report, after searching for duplicate reports.
However, please first try to verify that the problem is not with your local connection or network settings. Visit [Minecraft Community Support|https://discord.gg/58Sxm23] for assistance.
You might also try to deactivate any VPN in use, and check your firewall settings. If your device supports mobile data, try switching to wifi.
[standard links]

**Comment by NeunEinser** [comment]
We have this for "auth server down". Maybe it could be generalized?

```
*Thank you for your report!*
However, this issue is {color:#FF5722}*Invalid*{color}.

The authentication services are offline.
This will be fixed shortly, please hang tight. Check tweets from [@MojangSupport|https://twitter.com/MojangSupport] for the current status.

*Quick Links*:
📓 [Issue Guidelines|https://bugs.mojang.com/projects/MC/summary] -- 💬 [Community Support|https://discord.gg/58Sxm23] -- 📧 [Customer Support|https://help.minecraft.net/hc/en-us/requests/new] -- ✍️ [Feedback and Suggestions|https://feedback.minecraft.net/] -- 📖 [Game Wiki|https://minecraft.gamepedia.com/Minecraft_Wiki]
```

**Comment by Marcono1234** [comment]
The messages have different meanings though, the one by @MikeUnverferth says there _might_ be an outage while the existing one for "auth server down" confirms that there is an outage and that it will be fixed shortly.

---

>service availability issues related to Marketplace, Realms, and Servers

Is "Servers" supposed to cover third-party servers? If so it might not be good to send people to Mojang Support for this. Otherwise, if this is only about authentication servers it would be good to clarify this.

**Comment by MikeUnverferth** [comment]
I wouldn't use it for 3rd-party servers themselves being down, but sometimes there is a general outage where players can't connect to anything. Most likely this is because some identification service like Xbox Live is having temporary issues. But it's fine by me if want to remove "servers" from the list.
