### ISSUE TITLE
"Mojang Customer Support" vs "Customer Support"

### ISSUE THREAD

**Issue by Marcono1234** [mojira/helper-messages#93]
A few messages use "Mojang Cusomter Support" while others including the quick links only use the term "Customer Support".
Maybe it would be good to make this consistent.

If I recall correctly this was discussed a little bit internally before and one argument for "Mojang Customer Support" was that it makes it more clear that this is the official support provided by Mojang.
What are your opinions?

**Comment by NeunEinser** [comment]
I agree that Mojang Customer Support highlights the difference a bit better. Of course, this change should then also be applied to the quick links.

**Comment by SPGoding** [comment]
Yes I agree. Both Customer Support and Community Support start with "Cu", which makes them harder to recognize. Though imo "Mojang Customer Support" is a bit long, maybe we can abbreviate that to `Mojang Support`?

**Comment by MikeUnverferth** [comment]
That's clear and still shorter.
