### ISSUE TITLE
Combine messages 'contact-support' (MCPE) and 'account-issue'

### ISSUE THREAD

**Issue by Marcono1234** [mojira/helper-messages#94]
For MCPE there are currently two messages for account issues:
`contact-support`:
https://github.com/mojira/helper-messages/blob/043756d23f3d37ed31bb3cb6507b986d5bfaf9ac/assets/messages.yml#L206-L214
`account-issue` (used for other projects as well):
https://github.com/mojira/helper-messages/blob/043756d23f3d37ed31bb3cb6507b986d5bfaf9ac/assets/messages.yml#L57-L73

Maybe it would make sense to remove the MCPE specific `contact-support` message and include the following in `account-issue`:
- Also for billing
- Use "Mojang Customer Support" instead of only "Customer Support" (see also #93)?

**Comment by NeunEinser** [comment]
In case this gets resolved before #93, I think we should keep Customer Support, as that's what we usually use.

Other than that, I see no reason to have them seperated, as billing issues are always for Customer Support, not just in mcpe.

**Comment by MikeUnverferth** [comment]
It would be clearer if this were labeled as either "Customer Support" or "Mojang Support" in the selection list to more clearly distinguish it from "Technical Support Issue" (which could be shortened to just "Technical Support").
